### ISSUE TITLE
Tried to implement it using opencv2 or PIL

### ISSUE THREAD

**Issue by krishnavpai** [pushpendrahpx/conversion-lamp#4]
Nice idea of creating this app @pushpendrahpx and as you said one's privacy and data should never be compromised.
I tried to implement image quality reduction using python, so can I please add it?

Also, another naive way is to simply use MS Paint or any such alternative.

**Comment by pushpendrahpx** [comment]
Hi @krishnavpai, Actually we are focused on building truly offline PWA for any device, which should be available for users just like visiting websites & Having offline access, and all these conditions are getting covered by making PWA, so we are building that, and the technologies required for that, will be most of the Javascript, so is there any suggestion how will be able to integrate your image reduction program in python ?

**Comment by pushpendrahpx** [comment]
> Nice idea of creating this app @pushpendrahpx and as you said one's privacy and data should never be compromised. I tried to implement image quality reduction using python, so can I please add it?
> 
> Also, another naive way is to simply use MS Paint or any such alternative.

Also, I thought to create own modules which will be able to convert files, but it seems, there are libraries already available there in NPM, which offers different types of image & document conversion libraries, so using those for project would be beneficial, it will save costs in terms of time.

**Comment by krishnavpai** [comment]
Got your point.
Thanks
